# Generated by Django 4.1.3 on 2023-09-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_remove_userprofile_registration_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
