# Generated by Django 4.1.3 on 2023-01-17 11:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import new_life.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="profile_photo/profile_placeholder.jpg",
                        upload_to="profile_photo/patient/",
                        validators=[new_life.validators.validate_file_size],
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="AE"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100)),
                (
                    "eid",
                    models.CharField(
                        max_length=18,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Emirates ID must be in format 111-1111-1111111-1",
                                regex="^(\\d{1,3}(-(\\d{1,4}(-(\\d{1,7}(-(\\d{1,1})?)?)?)?)?)?)$",
                            )
                        ],
                        verbose_name="Emirates ID",
                    ),
                ),
                (
                    "registration_date_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
